server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dairy
    username: root
    password: 123

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  jackson:
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台日志打印类型
  global-config:
    db-config:
      id-type: auto


fast-alden:
  file:
    oss:
      qiniu:
        access-key: Jbd1BbP_sCgocohDMhD1H-Uevi_saXZ6HDBOk8vF # 请从七牛云工作台-个人中心-密钥管理获取
        secret-key: ZsCHfzInaVv84EWYOxGV1x6Q-7lAHQgA8JHtPWZW # 请从七牛云工作台-个人中心-密钥管理获取
        bucket: lum # 七牛云存储空间名称
        directory: dm/image/ # 自定义存储空间内目录
        domain: http://se70bycel.hb-bkt.clouddn.com/
